from pathlib import Path
import json
from openai import OpenAI

ROOT = Path('/home/ubuntu/sourcingally')
OUT = ROOT / 'src/data/knowledge-ui-locales.ts'
client = OpenAI()
source = {
  'sections': {
    'services': {'label':'Sourcing services','kicker':'Work with us','title':'China sourcing is a chain of decisions—not one search.','intro':'A useful sourcing partner helps you move from an uncertain product idea to clearer supplier decisions, samples, factory conversations, quality checks, packaging, and the next logistics step.','framework':['Define the brief','Find and compare','Verify and sample','Manage production','Check and prepare'],'panelCode':'BRIEF / CHECK','panelTitle':'Make the next decision','panelText':'A sequence that keeps supplier work moving.','storyTitle':'The supplier is only one part of the work.','storyText':'A supplier search can produce names and prices. A managed process helps you understand whether a supplier fits the requirement, whether the sample is meaningful, what should be checked during production, and what needs to be agreed before goods move.','toolQuestions':['What exactly do I need the supplier or partner to decide?','What must be checked before I pay or approve production?','What information can I provide in a product brief?','What would make this project unsuitable?']},
    'products': {'label':'Product sourcing','kicker':'Product intelligence','title':'Start with the product. Then find the place, process, and partner.','intro':'Different products create different sourcing questions. Materials, tooling, testing, packaging, MOQ, and destination-market obligations all change the way a project should be researched.','framework':['Material & use','Manufacturing method','Supplier questions','Quality checkpoints','Market requirements'],'panelCode':'PRODUCT / PROOF','panelTitle':'Know what to check','panelText':'Materials, process, samples, quality, and destination questions.','storyTitle':'The same sourcing method does not fit every product.','storyText':'A product category is a set of manufacturing choices. The right page should help you think about materials, production methods, samples, quality, packaging, and market requirements before you compare quotations.','toolQuestions':['What is the product made from and how will it be used?','What could vary between a sample and mass production?','What packaging protects the product in real shipping?','Which destination-market questions must be checked?']},
    'cities': {'label':'China manufacturing cities','kicker':'China on the ground','title':'A city name is a starting point—not a supplier guarantee.','intro':'China’s manufacturing geography is connected by clusters, markets, factories, logistics, and specialist processes. Use location research to plan better questions and more useful visits.','framework':['Choose the region','Find the process','Verify the address','Plan the route','Document the visit'],'panelCode':'CN / ROUTE','panelTitle':'On the ground','panelText':'Markets, clusters, addresses, and practical travel questions.','storyTitle':'Location research becomes useful when it changes your questions.','storyText':'A location can point you toward a cluster, market, process, or travel route. It cannot replace supplier verification. Use city knowledge to plan the right visit and ask for the evidence that matters.','toolQuestions':['What process or supplier capability am I looking for?','Do I know the actual factory address?','What should I photograph, record, or ask during a visit?','What is the next decision after I return?']},
    'guides': {'label':'China sourcing education','kicker':'Sourcing school','title':'Learn the system before you place the order.','intro':'The most expensive sourcing mistakes often begin before production: unclear requirements, weak supplier comparisons, untested assumptions, or confusion about responsibility. Start with a structured path.','framework':['Start here','Find suppliers','Develop samples','Control quality','Ship and review'],'panelCode':'LEARN / APPLY','panelTitle':'Build your method','panelText':'A clearer path from first question to confident action.','storyTitle':'Education gives you better decisions, not just more information.','storyText':'A good guide should help you define the next action. Read the sequence, write down your own assumptions, compare the options, and then ask for help with a specific question rather than a vague request.','toolQuestions':['What is my product, quantity, destination, and timeline?','How will I compare suppliers on the same requirements?','Which sample and quality checks are necessary?','Who is responsible for customs, testing, and compliance?']},
  },
  'common': {'startProject':'Start with your project ↗','seeFramework':'See the framework ↓','fieldNote':'FIELD NOTE','scroll':'SCROLL TO EXPLORE','frameworkKicker':'The way to think about it','frameworkTitle':'Useful sourcing has a sequence.','frameworkCopy':'Use this framework to understand what comes before the next decision. Each step connects to a deeper guide and a practical action.','storyKicker':'Why this matters','storyNote':'Sourcing Ally is based in Shenzhen and supports international buyers with agreed project work across China.','startHere':'Start here','featuredTitle':'Three useful doorways into this topic.','featuredCopy':'These are not advertisements. They are starting points chosen to help you understand the subject before you decide what to do.','readGuide':'Read the full guide ↗','toolKicker':'Practical tool','toolTitle':'Before you click “contact supplier”.','toolCopy':'Write down these questions first. They will make your research, quotation comparison, and first conversation much more useful.','beginnerGuide':'Open the beginner guide ↗','libraryKicker':'Explore the library','libraryTitle':'Go deeper when you are ready.','libraryCopy':'The full library is organized so the next page answers the question that naturally follows the one you are reading.','faqKicker':'Questions buyers ask','faqTitle':'Clear answers before a real conversation.','closeKicker':'Make it specific','closeTitle':'Tell us what you are trying to source.','closeCopy':'Email the product, quantity, destination, timing, and the question you are trying to answer. We will discuss the next practical step.','contact':'Contact Sourcing Ally ↗',
    'detail': {'back':'← {sectionLabel}','before':'Before you begin','checklist':'A useful decision checklist','next':'What to do next','connect':'Connect the next decision','connectTitle':'Use this page as part of a clearer sourcing plan.','official':'Official resources','officialTitle':'Further reading for current trade-term questions.','officialCopy':'These sources are provided for educational context. They do not replace advice for your product, destination, transaction, or import role.','note':'Important note','noteCopy':'Information on this page is general education, not legal, customs, tax, testing, or professional compliance advice. Requirements depend on the product and destination market and should be checked before you order or sell.','questions':'Questions buyers ask','help':'Need help in China?','helpCopy':'Sourcing Ally is based in Shenzhen. When a client orders through Sourcing Ally, the minimum sourcing service fee is 5%. Independent factory-travel support is available at $150 per day when the client does not order through Sourcing Ally.','contact':'Contact Sourcing Ally ↗','relatedKicker':'Continue learning','relatedTitle':'Related topics','relatedCopy':'Build a clearer sourcing plan by connecting the right questions, services, and locations.','read':'Read guide ↗'}}
}
targets={'es':'neutral, natural Latin American Spanish','pt':'natural professional Brazilian Portuguese','ru':'clear professional Russian; use Russian script for all non-brand reader-facing labels','tr':'clear professional Turkish','fr':'natural professional international French'}
# Schema mirrors the source precisely but permits nested section and common objects.
string={'type':'string'}
section_props={key:{'type':'object','properties':{'label':string,'kicker':string,'title':string,'intro':string,'framework':{'type':'array','items':string},'panelCode':string,'panelTitle':string,'panelText':string,'storyTitle':string,'storyText':string,'toolQuestions':{'type':'array','items':string}},'required':['label','kicker','title','intro','framework','panelCode','panelTitle','panelText','storyTitle','storyText','toolQuestions'],'additionalProperties':False} for key in source['sections']}
detail_props={key:string for key in source['common']['detail']}
common_props={key:string for key in source['common'] if key!='detail'}
common_props['detail']={'type':'object','properties':detail_props,'required':list(detail_props),'additionalProperties':False}
schema={'type':'json_schema','json_schema':{'name':'knowledge_ui_locales','strict':True,'schema':{'type':'object','properties':{'sections':{'type':'object','properties':section_props,'required':list(section_props),'additionalProperties':False},'common':{'type':'object','properties':common_props,'required':list(common_props),'additionalProperties':False}},'required':['sections','common'],'additionalProperties':False}}}
system='You are a senior website localization editor. Translate every visible public website interface string into the target language. Preserve only the Sourcing Ally brand and the approved figures 5% and $150 per day. Do not add claims. Use natural professional copy. Return only JSON matching the schema.'
output={'en':source}
for code,target in targets.items():
    r=client.chat.completions.create(model='gpt-5-mini',messages=[{'role':'system','content':system},{'role':'user','content':f'Target: {target}.\n\nSource:\n{json.dumps(source,ensure_ascii=False)}'}],response_format=schema,max_completion_tokens=14000)
    data=json.loads(r.choices[0].message.content)
    for section in source['sections']:
        if len(data['sections'][section]['framework']) != 5 or len(data['sections'][section]['toolQuestions']) != 4:
            raise RuntimeError(f'{code}/{section}: structure mismatch')
    output[code]=data
    print(f'Generated {code}')
OUT.write_text('export const knowledgeUiLocales = '+json.dumps(output,ensure_ascii=False,indent=2)+' as const;\n',encoding='utf-8')
print(f'Wrote {OUT}')
